import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AddUser from '../components/userForm'
import Instructions from '../components/instructions'
import classes from '../styles/extra.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hungry_cat_icon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Bienvenido! </h1>

        <h3>Test - Memoria a corto plazo</h3>
        <Instructions />
        <div className={classes.form}>
          <AddUser />
        </div>
      </main>

      <footer className={styles.footer}>
      <p></p>
      </footer>
    </div>
  )
}
