import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AddUser from '../components/userForm'
import Instructions from '../components/instructions'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1> Bienvenido! </h1>

        <h3>Test - Memoria a corto plazo</h3>

        <p className={styles.description}>

        </p>

        <Instructions/>
        
        <AddUser/>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
